/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Amount = IDL.Float64;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'upiId' : IDL.Text,
  'phone' : IDL.Text,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'receive' : IDL.Null,
  'bill' : IDL.Null,
  'request' : IDL.Null,
  'send' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : TransactionStatus,
  'provider' : IDL.Text,
  'note' : IDL.Text,
  'type' : TransactionType,
  'receiverId' : UserId,
  'timestamp' : Time,
  'category' : IDL.Text,
  'accountNumber' : IDL.Text,
  'amount' : Amount,
  'senderId' : UserId,
});
export const Phone = IDL.Text;
export const UpiId = IDL.Text;
export const User = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'upiId' : UpiId,
  'phone' : Phone,
  'walletBalance' : Amount,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBalance' : IDL.Func([], [Amount], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserByPhone' : IDL.Func([Phone], [IDL.Opt(User)], ['query']),
  'getUserByUpi' : IDL.Func([UpiId], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTransactions' : IDL.Func([UserId], [IDL.Vec(Transaction)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'payBill' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Amount], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [User], []),
  'requestMoney' : IDL.Func([UpiId, Amount, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMoney' : IDL.Func([UpiId, Amount, IDL.Text], [], []),
  'topUp' : IDL.Func([Amount], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Amount = IDL.Float64;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'upiId' : IDL.Text,
    'phone' : IDL.Text,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'receive' : IDL.Null,
    'bill' : IDL.Null,
    'request' : IDL.Null,
    'send' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : TransactionStatus,
    'provider' : IDL.Text,
    'note' : IDL.Text,
    'type' : TransactionType,
    'receiverId' : UserId,
    'timestamp' : Time,
    'category' : IDL.Text,
    'accountNumber' : IDL.Text,
    'amount' : Amount,
    'senderId' : UserId,
  });
  const Phone = IDL.Text;
  const UpiId = IDL.Text;
  const User = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'upiId' : UpiId,
    'phone' : Phone,
    'walletBalance' : Amount,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBalance' : IDL.Func([], [Amount], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserByPhone' : IDL.Func([Phone], [IDL.Opt(User)], ['query']),
    'getUserByUpi' : IDL.Func([UpiId], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTransactions' : IDL.Func(
        [UserId],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'payBill' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Amount], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [User], []),
    'requestMoney' : IDL.Func([UpiId, Amount, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMoney' : IDL.Func([UpiId, Amount, IDL.Text], [], []),
    'topUp' : IDL.Func([Amount], [], []),
  });
};

export const init = ({ IDL }) => { return []; };