/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Amount = number;
export type Phone = string;
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'status' : TransactionStatus,
  'provider' : string,
  'note' : string,
  'type' : TransactionType,
  'receiverId' : UserId,
  'timestamp' : Time,
  'category' : string,
  'accountNumber' : string,
  'amount' : Amount,
  'senderId' : UserId,
}
export type TransactionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type TransactionType = { 'receive' : null } |
  { 'bill' : null } |
  { 'request' : null } |
  { 'send' : null };
export type UpiId = string;
export interface User {
  'id' : UserId,
  'name' : string,
  'createdAt' : Time,
  'upiId' : UpiId,
  'phone' : Phone,
  'walletBalance' : Amount,
}
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'upiId' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getBalance' : ActorMethod<[], Amount>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserByPhone' : ActorMethod<[Phone], [] | [User]>,
  'getUserByUpi' : ActorMethod<[UpiId], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTransactions' : ActorMethod<[UserId], Array<Transaction>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'payBill' : ActorMethod<[string, string, string, Amount], undefined>,
  'registerUser' : ActorMethod<[string, string], User>,
  'requestMoney' : ActorMethod<[UpiId, Amount, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMoney' : ActorMethod<[UpiId, Amount, string], undefined>,
  'topUp' : ActorMethod<[Amount], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];